# Generated by Django 2.2 on 2019-05-11 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190510_1425'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assign',
            table='assign',
        ),
        migrations.AlterModelTable(
            name='enroll',
            table='enroll',
        ),
    ]
