# Generated by Django 2.2 on 2019-05-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190513_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissionstate',
            fields=[
                ('perstatenumber', models.IntegerField(primary_key=True, serialize=False)),
                ('perstatename', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Permissionstate',
                'managed': False,
            },
        ),
    ]
