# Generated by Django 2.2 on 2019-05-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20190521_1104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
