# Generated by Django 2.2 on 2019-05-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190511_1111'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assign',
            table='Assign',
        ),
        migrations.AlterModelTable(
            name='enroll',
            table='Enroll',
        ),
    ]
