# Generated by Django 2.2 on 2019-05-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_setion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('token', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('expiretime', models.DateTimeField()),
            ],
            options={
                'db_table': 'Session',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Setion',
        ),
    ]
