# Generated by Django 2.2 on 2019-05-18 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20190518_1512'),
        ('posts', '0007_session'),
    ]

    operations = [
    ]
