# Generated by Django 2.2 on 2019-05-21 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'managed': False},
        ),
    ]
